spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # üî• Ïù¥Î©îÏùº Ïù∏Ï¶ùÏö© Î©îÏùº ÏÑ§Ï†ï Ï∂îÍ∞Ä
  mail:
    host: smtp.gmail.com
    port: 587
    username: hyn960320@gmail.com
    password: jkqg xyub aepx nzxy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_CHANGE_ME_CHANGE_ME"
    access-token-exp-min: 120

ai:
  provider: real

ai-server:
  base-url: http://localhost:8010

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-2
    s3:
      bucket: skincheck-images

deepseek:
  api-key: "sk-25e6993e099545988b7e1c4711077339"
  model: deepseek-chat

naver:
  client-id: w_1Px893pTuZr1QF8pFK
  client-secret: 9XIRbPcc1c
