spring:
  profiles:
    active: dev

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_CHANGE_ME_CHANGE_ME"
    access-token-exp-min: 120

ai:
  provider: real

ai-server:
  base-url: http://localhost:8000
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-2
    s3:
      bucket: skincheck-images